modLoader = "javafml"
loaderVersion = "[1,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "icon.png"
description = '''
Addon for Create: Power Grid adding nested circuit board chip components.
'''

[[mixins]]
config = "powerchip.mixins.json"

[[dependencies.powerchip]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.powerchip]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.powerchip]]
modId = "powergrid"
type = "required"
versionRange = "[${powergrid_version},)"
ordering = "AFTER"
side = "BOTH"

